#' Turn a transmssion tree into a graph object
#'
#' @param ttree data.table with columns `id_progen` (id of case progenitor),
#' `id_case` (id of case), `t` (date of case), `x_coord`, and `y_coord`
#'
#' @return a graph generated by igraph
#' @export
#'
get_graph <- function(ttree) {

  from <- tree$id_progen
  to <- tree$id_case
  I_gr <- data.table(from = from[!is.na(from)], to = to[!is.na(from)])
  gr <- graph_from_data_frame(d = I_gr,
                              vertices = tree[, .(id_case,
                                                  t = t - min(t), x_coord, y_coord)],
                              directed = TRUE)
  V(gr)$membership <- components(gr)$membership
  return(gr)
}


#' Get chain size & lengths
#'
#' @param gr graph of transmission tree
#'
#' @return a data.table with membership (i.e. chain id), chain size, and chain length
#' @export
#'
get_chain_stats <- function(gr) {

  comps <- components(gr)
  return(data.table(membership = seq(comps$no), size = comps$csize,
                    length = unlist(lapply(decompose(gr), diameter))))
}


#' Get membership (i.e. chain id) for each case
#'
#' @inheritParams get_chain_size
#'
#' @return a data.table with id_case, membership, and t_days (time in days from
#'  the start date, i.e. the earliest case in the transmission tree)
#' @export
#'
get_chain_membership <- function(gr) {

  return(
    data.table(membership = vertex_attr(exe_gr, "membership"),
               id_case = vertex_attr(gr, "name"),
               t_days = vertex_attr(gr, "t"))
  )
}


#' Get duration of chain persistence in days
#'
#' @param chain_membership output from `get_chain_membership` (a data.table
#'  with the membership of each case and the time in days)
#'
#' @return a data.table with the start and end days (from the origin, i.e. minimum
#'  case date in the transmission tree) and the duration of the chain in days.
#' @export
#'
get_chain_persistence <- function(chain_membership) {

  chain_pers <- chain_id[, .(start_date = min(t), end_date = max(t)), by = "membership"]
  chain_pers[, days := end_date - start_date]
  return(chain_pers)
}
